//------------------------------------------------------------------------------
//  OBD.Design.Starters.RadioPolished
//
//  Polished radio-calculator form template.
//
//  Layout matches the canonical ERDesigns standalone calculator
//  shape (logo header / serial input row / radio-code output
//  row / About + Calculate button bar). All vendor-specific
//  text is set in FormCreate via the dropped TOBDRadioCode
//  component's DisplayName / BrandKey, so swapping the calc
//  class to a different vendor renames every visible string
//  automatically.
//
//  Reference DFM:
//    https://github.com/erdesigns-eu/Peugeot-Calculator/blob/main/untMain.dfm
//
//  Author      : Ernst Reidinga (ERDesigns)
//  Copyright   : (c) 2026 Ernst Reidinga (ERDesigns) and Delphi-OBD contributors
//  License     : MIT - see LICENSE
//------------------------------------------------------------------------------

unit OBD.Design.Starters.RadioPolished;

interface

implementation

uses
  System.SysUtils,
  System.Classes,
  OBD.Design.Starters;

function Expand(const ATemplate: string;
  const AContext: TOBDStarterContext): string; inline;
begin
  Result := ExpandTemplate(ATemplate, AContext);
end;

function MakeDpr(const AContext: TOBDStarterContext): TOBDStarterArtifact; inline;
begin
  Result := MakeDprArtifact(AContext);
end;

function GenerateRadioPolished(
  const AContext: TOBDStarterContext): TArray<TOBDStarterArtifact>;
const
  PAS_TPL =
    '//---------------------------------------------------------------------------'#13#10 +
    '// Radio-code calculator (polished template).'#13#10 +
    '// Generated by Delphi-OBD wizard. Layout based on'#13#10 +
    '//   github.com/erdesigns-eu/Peugeot-Calculator'#13#10 +
    '//---------------------------------------------------------------------------'#13#10 +
    'unit {UNIT};'#13#10#13#10 +
    'interface'#13#10#13#10 +
    'uses'#13#10 +
    '  Winapi.Windows, Winapi.Messages,'#13#10 +
    '  System.SysUtils, System.Classes,'#13#10 +
    '  Vcl.Graphics, Vcl.Controls, Vcl.Forms, Vcl.Dialogs,'#13#10 +
    '  Vcl.StdCtrls, Vcl.ExtCtrls, Vcl.Imaging.pngimage,'#13#10 +
    '  OBD.RadioCode.Types, OBD.RadioCode,'#13#10 +
    '  OBD.RadioCode.FrenchItalian;'#13#10#13#10 +
    'type'#13#10 +
    '  /// <summary>Radio-code calculator main form.</summary>'#13#10 +
    '  {FORM} = class(TForm)'#13#10 +
    '    bvImageLine:     TBevel;'#13#10 +
    '    imgLogo:         TImage;'#13#10 +
    '    pnlBottom:       TPanel;'#13#10 +
    '    bvPnlLine:       TBevel;'#13#10 +
    '    btnAbout:        TButton;'#13#10 +
    '    btnCalculate:    TButton;'#13#10 +
    '    pnlSerialNumber: TPanel;'#13#10 +
    '    lblSerialNumber: TLabel;'#13#10 +
    '    edtSerialNumber: TEdit;'#13#10 +
    '    pnlRadioCode:    TPanel;'#13#10 +
    '    lblRadioCode:    TLabel;'#13#10 +
    '    edtRadioCode:    TEdit;'#13#10 +
    '    Calc:            TOBDRadioCodePeugeot;'#13#10 +
    '    procedure FormCreate(Sender: TObject);'#13#10 +
    '    procedure btnCalculateClick(Sender: TObject);'#13#10 +
    '    procedure btnAboutClick(Sender: TObject);'#13#10 +
    '  end;'#13#10#13#10 +
    'var {FORMVAR}: {FORM};'#13#10#13#10 +
    'implementation'#13#10#13#10 +
    '{$R *.dfm}'#13#10#13#10 +
    'procedure {FORM}.FormCreate(Sender: TObject);'#13#10 +
    'begin'#13#10 +
    '  // Use the dropped calculator''s DisplayName so every visible'#13#10 +
    '  // string updates automatically when the host swaps the'#13#10 +
    '  // Calc component class to a different vendor.'#13#10 +
    '  Caption := Calc.DisplayName + '' radio code calculator'';'#13#10 +
    '  Application.Title := Caption;'#13#10 +
    '  lblSerialNumber.Caption := ''Serial / barcode:'';'#13#10 +
    '  lblRadioCode.Caption    := ''Radio code:'';'#13#10 +
    '  btnCalculate.Caption    := ''Calculate'';'#13#10 +
    '  btnAbout.Caption        := ''About'';'#13#10 +
    '  edtSerialNumber.Text    := '''';'#13#10 +
    '  edtRadioCode.Text       := '''';'#13#10 +
    'end;'#13#10#13#10 +
    'procedure {FORM}.btnCalculateClick(Sender: TObject);'#13#10 +
    'var R: TOBDRadioCodeResult;'#13#10 +
    'begin'#13#10 +
    '  Calc.Input := edtSerialNumber.Text;'#13#10 +
    '  R := Calc.Calculate;'#13#10 +
    '  if R.Success then'#13#10 +
    '    edtRadioCode.Text := R.Code'#13#10 +
    '  else'#13#10 +
    '  begin'#13#10 +
    '    edtRadioCode.Text := '''';'#13#10 +
    '    MessageBox(Handle, PChar(R.Message), PChar(Caption),'#13#10 +
    '      MB_ICONWARNING + MB_OK);'#13#10 +
    '  end;'#13#10 +
    'end;'#13#10#13#10 +
    'procedure {FORM}.btnAboutClick(Sender: TObject);'#13#10 +
    'var About: string;'#13#10 +
    'begin'#13#10 +
    '  About :='#13#10 +
    '    Calc.DisplayName + '' radio code calculator''  + sLineBreak + sLineBreak +'#13#10 +
    '    ''Built with Delphi-OBD - github.com/erdesigns-eu/Delphi-OBD'' + sLineBreak + sLineBreak +'#13#10 +
    '    Calc.Description;'#13#10 +
    '  MessageBox(Handle, PChar(About), PChar(Caption),'#13#10 +
    '    MB_ICONINFORMATION + MB_OK);'#13#10 +
    'end;'#13#10#13#10 +
    'end.'#13#10;

  // Verbatim transcription of the Peugeot-Calculator DFM layout
  // with vendor-specific bits removed (logo image data empty,
  // captions placeholder so FormCreate sets them, MaxLength
  // dropped from edtSerialNumber, ReadOnly stays on edtRadioCode).
  DFM_TPL =
    'object {FORMVAR}: {FORM}'#13#10 +
    '  Left = 0'#13#10 +
    '  Top = 0'#13#10 +
    '  BorderIcons = [biSystemMenu, biMinimize]'#13#10 +
    '  BorderStyle = bsSingle'#13#10 +
    '  Caption = ''{PROJ}'''#13#10 +
    '  ClientHeight = 262'#13#10 +
    '  ClientWidth = 388'#13#10 +
    '  Color = clBtnFace'#13#10 +
    '  Font.Charset = DEFAULT_CHARSET'#13#10 +
    '  Font.Color = clWindowText'#13#10 +
    '  Font.Height = -12'#13#10 +
    '  Font.Name = ''Segoe UI'''#13#10 +
    '  Font.Style = []'#13#10 +
    '  Position = poScreenCenter'#13#10 +
    '  OnCreate = FormCreate'#13#10 +
    '  TextHeight = 15'#13#10 +
    '  object bvImageLine: TBevel'#13#10 +
    '    AlignWithMargins = True'#13#10 +
    '    Left = 0  Top = 136  Width = 388  Height = 2'#13#10 +
    '    Margins.Left = 0  Margins.Top = 0  Margins.Right = 0  Margins.Bottom = 6'#13#10 +
    '    Align = alTop  Shape = bsTopLine'#13#10 +
    '  end'#13#10 +
    '  object imgLogo: TImage'#13#10 +
    '    Left = 0  Top = 0  Width = 388  Height = 136'#13#10 +
    '    Align = alTop  Center = True'#13#10 +
    '    // TODO: assign Picture.LoadFromFile(...) at design'#13#10 +
    '    // time to brand the form with your vendor logo.'#13#10 +
    '  end'#13#10 +
    '  object pnlBottom: TPanel'#13#10 +
    '    Left = 0  Top = 219  Width = 388  Height = 43'#13#10 +
    '    Align = alBottom  BevelOuter = bvNone  ShowCaption = False  TabOrder = 0'#13#10 +
    '    object bvPnlLine: TBevel'#13#10 +
    '      AlignWithMargins = True'#13#10 +
    '      Left = 8  Top = 0  Width = 372  Height = 2'#13#10 +
    '      Margins.Left = 8  Margins.Top = 0  Margins.Right = 8  Margins.Bottom = 0'#13#10 +
    '      Align = alTop  Shape = bsTopLine'#13#10 +
    '    end'#13#10 +
    '    object btnAbout: TButton'#13#10 +
    '      AlignWithMargins = True'#13#10 +
    '      Left = 280  Top = 10  Width = 100  Height = 25'#13#10 +
    '      Margins.Left = 0  Margins.Top = 8  Margins.Right = 8  Margins.Bottom = 8'#13#10 +
    '      Align = alRight  Caption = ''About''  TabOrder = 1  OnClick = btnAboutClick'#13#10 +
    '    end'#13#10 +
    '    object btnCalculate: TButton'#13#10 +
    '      AlignWithMargins = True'#13#10 +
    '      Left = 176  Top = 10  Width = 100  Height = 25'#13#10 +
    '      Margins.Left = 0  Margins.Top = 8  Margins.Right = 4  Margins.Bottom = 8'#13#10 +
    '      Align = alRight  Caption = ''Calculate''  Default = True  TabOrder = 0  OnClick = btnCalculateClick'#13#10 +
    '    end'#13#10 +
    '  end'#13#10 +
    '  object pnlSerialNumber: TPanel'#13#10 +
    '    Left = 0  Top = 144  Width = 388  Height = 29'#13#10 +
    '    Align = alTop  BevelOuter = bvNone  ShowCaption = False  TabOrder = 1'#13#10 +
    '    object lblSerialNumber: TLabel'#13#10 +
    '      AlignWithMargins = True'#13#10 +
    '      Left = 8  Top = 4  Width = 100  Height = 21'#13#10 +
    '      Margins.Left = 8  Margins.Top = 4  Margins.Right = 0  Margins.Bottom = 4'#13#10 +
    '      Align = alLeft  AutoSize = False  Layout = tlCenter'#13#10 +
    '      Caption = ''Serial / barcode:'''#13#10 +
    '    end'#13#10 +
    '    object edtSerialNumber: TEdit'#13#10 +
    '      AlignWithMargins = True'#13#10 +
    '      Left = 116  Top = 4  Width = 264  Height = 21'#13#10 +
    '      Margins.Left = 8  Margins.Top = 4  Margins.Right = 8  Margins.Bottom = 4'#13#10 +
    '      Align = alClient  CharCase = ecUpperCase  TabOrder = 0'#13#10 +
    '    end'#13#10 +
    '  end'#13#10 +
    '  object pnlRadioCode: TPanel'#13#10 +
    '    Left = 0  Top = 173  Width = 388  Height = 29'#13#10 +
    '    Align = alTop  BevelOuter = bvNone  ShowCaption = False  TabOrder = 2'#13#10 +
    '    object lblRadioCode: TLabel'#13#10 +
    '      AlignWithMargins = True'#13#10 +
    '      Left = 8  Top = 4  Width = 100  Height = 21'#13#10 +
    '      Margins.Left = 8  Margins.Top = 4  Margins.Right = 0  Margins.Bottom = 4'#13#10 +
    '      Align = alLeft  AutoSize = False  Layout = tlCenter'#13#10 +
    '      Caption = ''Radio code:'''#13#10 +
    '    end'#13#10 +
    '    object edtRadioCode: TEdit'#13#10 +
    '      AlignWithMargins = True'#13#10 +
    '      Left = 116  Top = 4  Width = 264  Height = 21'#13#10 +
    '      Margins.Left = 8  Margins.Top = 4  Margins.Right = 8  Margins.Bottom = 4'#13#10 +
    '      Align = alClient  ReadOnly = True  TabOrder = 0'#13#10 +
    '    end'#13#10 +
    '  end'#13#10 +
    '  object Calc: TOBDRadioCodePeugeot Left = 24 Top = 232 end'#13#10 +
    'end'#13#10;
var
  Pas, Dfm: TOBDStarterArtifact;
begin
  SetLength(Result, 3);
  Result[0] := MakeDpr(AContext);
  Pas := Default(TOBDStarterArtifact);
  Pas.RelativePath := AContext.UnitName + '.pas';
  Pas.Content := Expand(PAS_TPL, AContext);
  Result[1] := Pas;
  Dfm := Default(TOBDStarterArtifact);
  Dfm.RelativePath := AContext.UnitName + '.dfm';
  Dfm.Content := Expand(DFM_TPL, AContext);
  Result[2] := Dfm;
end;

procedure RegisterAll;
var S: TOBDStarter;
begin
  S := Default(TOBDStarter);
  S.Id := 'radio-calculator-polished';
  S.Title := 'Radio-code calculator (polished)';
  S.Description :=
    'Polished radio-code calculator form mirroring the canonical ' +
    'ERDesigns standalone-calculator layout: logo header + serial ' +
    'input + result + Calculate / About button bar. FormCreate ' +
    'pulls every visible string from the dropped Calc component''s ' +
    'DisplayName / Description, so swapping the Calc class to ' +
    'another vendor automatically rebrands the form.';
  S.Category := 'Radio';
  S.Generate := GenerateRadioPolished;
  TOBDStarterRegistry.Default.Register(S);
end;

initialization
  RegisterAll;

end.
